version: "1.0.0"
services:
  mongo_primary:
    image: mongo
    ports:
      - "2717:2717"
    command: mongod --port 2717 --replSet "rs0"
    environment:
      - MONGO_INITDB_REPLICASET=rs0
    restart: always
    networks:
      - mongo_replica
    volumes:
      - ./data/primary:/data/db
    depends_on:
      - "mongo_secondary-1"
      - "mongo_secondary-2"

  mongo_secondary-1:
    image: mongo
    command: mongod --port 2727 --replSet "rs0"
    ports:
      - "2727:2727"
    environment:
      - MONGO_INITDB_REPLICASET=rs0
    restart: always
    networks:
      - mongo_replica
    volumes:
      - ./data/secondary-1:/data/db

  mongo_secondary-2:
    image: mongo
    command: mongod --port 2737 --replSet "rs0"
    ports:
      - "2737:2737"
    environment:
      - MONGO_INITDB_REPLICASET=rs0
    restart: always
    networks:
      - mongo_replica
    volumes:
      - ./data/secondary-2:/data/db

  setup-rs:
    image: "mongo-rs-setup"
    build: ./setup
    networks:
      - mongo_replica
    depends_on:
      - "mongo_primary"

volumes:
  mongo_primary:
  mongo_secondary-1:
  mongo_secondary-2:

networks:
  mongo_replica:
    driver: bridge
