version: "3"

services:
  mdbrs0p:
    container_name: mdbrs0p
    image: mongo
    ports:
      - "2717:2717"
    command: mongod --replSet rs0 --port 2717 --dbpath /data/db
    environment:
      - MONGO_INITDB_REPLICASET=rs0
    restart: always
    networks:
      - mdbrs0
    volumes:
      - ./data/mdbrs0p:/data/db
    depends_on:
      - "mdbrs0s1"
      - "mdbrs0s2"

  mdbrs0s1:
    container_name: mdbrs0s1
    image: mongo
    command: mongod --replSet rs0 --port 2727 --dbpath /data/db
    ports:
      - "2727:2727"
    environment:
      - MONGO_INITDB_REPLICASET=rs0
    restart: always
    networks:
      - mdbrs0
    volumes:
      - ./data/mdbrs0s1:/data/db

  mdbrs0s2:
    container_name: mdbrs0s2
    image: mongo
    command: mongod --replSet rs0 --port 2737 --dbpath /data/db
    ports:
      - "2737:2737"
    environment:
      - MONGO_INITDB_REPLICASET=rs0
    restart: always
    networks:
      - mdbrs0
    volumes:
      - ./data/mdbrs0s2:/data/db

  mdbrs0setup:
    container_name: mdbrs0setup
    image: "mongo-rs-setup"
    build: ./setup
    networks:
      - mdbrs0
    depends_on:
      - "mdbrs0p"

volumes:
  mdbrs0p:
  mdbrs0s1:
  mdbrs0s2:

networks:
  mdbrs0:
    driver: bridge
